header:
  license:
    spdx-id: Apache-2.0
  text: |
    SPDX-FileCopyrightText: Copyright contributors to the kvcached project
    SPDX-License-Identifier: Apache-2.0
  language:
    Python: { style: Hash }        # -> "# …"
    C:      { style: SlashStar }    # -> "/* … */"
    C++:    { style: SlashStar }
    CUDA:   { style: SlashStar }