[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kvcached"
version = "0.1.0"
readme = "README.md"
dependencies = [
    "numpy>=1.26.0",
    "posix_ipc>=1.0",
]
requires-python = ">=3.9,<3.12"

[tool.setuptools]
packages = ["kvcached"]
