version = 1
SPDX-PackageName = "kvcached"
SPDX-PackageDownloadLocation = "."

[[annotations]]
path = ["**.md", "**/**.md", "**/**/**.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "contributors to the kvcached project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["**.yml", "**.yaml", "**/**.yml", "**/**.yaml", "**/**/**.yml", "**/**/**.yaml", ".github/workflows/**.yml", ".github/workflows/**.yaml", ".gemini/config.yaml", "controller/example-config.yaml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "contributors to the kvcached project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [".clang-format", ".gitignore", ".pre-commit-config.yaml", "MANIFEST.in", "pyproject.toml", "requirements.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "contributors to the kvcached project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["Dockerfile", "Dockerfile.**", "docker/Dockerfile**", "docker/README.md", "Makefile", "**/Makefile", "**/**/Makefile", "benchmarks/bench_vmm/Makefile"]
precedence = "aggregate"
SPDX-FileCopyrightText = "contributors to the kvcached project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["**.sh", "**/**.sh", "**/**/**.sh", "benchmarks/simple_bench/**.sh", "benchmarks/bench_kvcached_overhead/**.sh"]
precedence = "aggregate"
SPDX-FileCopyrightText = "contributors to the kvcached project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["engine_integration/patches/**", "kvcached_autopatch.pth"]
precedence = "aggregate"
SPDX-FileCopyrightText = "contributors to the kvcached project"
SPDX-License-Identifier = "Apache-2.0"
