# Referred to SkyRL
have_fun: true # the bot sometimes adds lighthearted / fun comments.
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: false # enable PR summaries
    code_review: false
ignore_patterns: []