kvcached: # kvcached环境变量（所有实例共享）
  kvcached_gpu_utilization: 0.95
  kvcached_page_prealloc_enabled: false  # 禁用预分配
  kvcached_min_reserved_pages: 0
  kvcached_max_reserved_pages: 0
  kvcached_sanity_check: false
  kvcached_log_level: INFO

router: # 路由器配置
  enable_router: true
  router_port: 8080
  router_host: localhost

instances: # 实例配置（禁用KVCached）
  - name: sglang-instance1
    model: meta-llama/Llama-3.2-1B
    engine: sglang
    using_venv: true
    venv_path: /workspace/kvcached/engine_integration/sglang-v0.4.9/.venv
    kvcached_env:
      - "ENABLE_KVCACHED=false"          # 禁用KVCached
      - "CUDA_VISIBLE_DEVICES=0"
    engine_env:
      - "TOKENIZERS_PARALLELISM=false"
      - "HF_HOME=/shared-models"
    engine_args:
      - "--disable-radix-cache"
      - "--trust-remote-code"
      - "--mem-fraction-static=0.30"     # 使用35%的GPU内存
      - "--host=0.0.0.0"
      - "--port=30333"
      - "--disable-cuda-graph"

  - name: sglang-instance2
    model: meta-llama/Llama-3.2-1B
    engine: sglang
    using_venv: true
    venv_path: /workspace/kvcached/engine_integration/sglang-v0.4.9/.venv
    kvcached_env:
      - "ENABLE_KVCACHED=false"          # 禁用KVCached
      - "CUDA_VISIBLE_DEVICES=0"
    engine_env:
      - "TOKENIZERS_PARALLELISM=false"
      - "HF_HOME=/shared-models"
    engine_args:
      - "--disable-radix-cache"
      - "--trust-remote-code"
      - "--mem-fraction-static=0.30"     # 使用35%的GPU内存
      - "--host=0.0.0.0"
      - "--port=30334"
      - "--disable-cuda-graph" 