kvcached: # kvcached environment variables for all instances
  kvcached_gpu_utilization: 0.95
  kvcached_page_prealloc_enabled: true
  kvcached_min_reserved_pages: 5
  kvcached_max_reserved_pages: 10
  kvcached_sanity_check: false
  kvcached_log_level: INFO
router: # router configuration
  enable_router: true
  router_port: 8080
  router_host: localhost
instances: # instances configuration
  - name: instance1
    model: meta-llama/Llama-3.2-1B
    engine: vllm
    using_venv: true
    venv_path:  /home/jrxing/kvcached/engine_integration/vllm-v0.9.2/.venv
    kvcached_env: # kvcached environment variables for this instance
      - "ENABLE_KVCACHED=true"
      - "KVCACHED_IPC_NAME=VLLM"
    engine_env:
      - "VLLM_USE_V1=1"
      - "VLLM_ATTENTION_BACKEND=FLASH_ATTN"
    engine_args:
      - "--disable-log-requests"
      - "--no-enable-prefix-caching"
      - "--host=localhost"
      - "--port=12346"
      - "--gpu-memory-utilization 0.5"
  - name: instance2
    model: Qwen/Qwen3-0.6B
    engine: sglang
    using_venv: true
    venv_path: /home/jrxing/kvcached/engine_integration/sglang-v0.4.6.post2/.venv
    kvcached_env:
      - "ENABLE_KVCACHED=true"
      - "KVCACHED_IPC_NAME=SGLANG"
    engine_args:
      - "--disable-radix-cache"
      - "--trust-remote-code"
      - "--mem-fraction-static 0.5"
      - "--host=localhost"
      - "--port=30000"