auto_sleep_enabled: true
check_interval_seconds: 60
idle_threshold_seconds: 300
min_sleep_duration: 120
sglang_models_config:
  Qwen/Qwen3-0.6B:
    host: localhost
    port: '30000'
vllm_models_config:
  meta-llama/Llama-3.2-1B:
    host: localhost
    port: '12346'
wakeup_on_request: true
