name: Pre-commit CI

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or match your local Python version

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
  # Run MyPy hooks across multiple Python versions
  mypy:
    name: MyPy (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pre-commit
        run: pip install pre-commit

      # Run only the mypy hook that matches this Python version (manual stage)
      - name: Run MyPy pre-commit hook
        run: pre-commit run --all-files --hook-stage manual mypy-${{ matrix.python-version }}